### ISSUE TITLE
Y-coordinates

### ISSUE THREAD

**Issue by SETHPROSYT** [Beez0r/WitherSpawn#2]
hello, I have a small problem, what happens is that when I put in the config the minimum level of string Y is for example 60, and I go between -59 and -51 the wither continues spawning, but if I go to the string - 49 the wither no longer spawns is there a way to fix it or what am I doing wrong
![imagen](https://github.com/Beez0r/WitherSpawn/assets/83810276/1e3c786b-1f0c-4abd-850c-7534ece1ef33)

**Comment by Beez0r** [comment]
I have just tested this with a fresh server install using the latest Minecraft paper version 1.19.4 and fresh Wither Spawn plugin install (version 1.7) only changing the config option of witherYCordMin to 60, the wither cannot be spawned at any Y level less than 60 after many attempts at various Y-levels below 60. What Minecraft and plugin version are you using? Can you share your config file?
